<a href="https://colab.research.google.com/github/bamSirikorn/BSC_DPDM2025/blob/main/Association_Rules_Group7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# นำเข้าข้อมูล

In [ ]:
import pandas as pd
import os

In [ ]:
import warnings
warnings.filterwarnings('ignore', message='.*datetime.datetime.utcnow().*', category=DeprecationWarning)
warnings.filterwarnings('ignore', message='.*SettingWithCopyWarning*', category=UserWarning)
warnings.filterwarnings('ignore', message='.*is a deprecated alias.*', category=FutureWarning)

In [ ]:
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path = '/content/drive/MyDrive/BSC_DPDM2025'

In [ ]:
India_data = pd.read_csv(os.path.join(path,'IMDb Movies India.csv'),encoding='latin-1')
India_data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,(1988),NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,(1999),129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15506,Zulmi Raj,(2005),NaN,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN
15507,Zulmi Shikari,(1988),NaN,Action,NaN,NaN,NaN,NaN,NaN,NaN
15508,Zulm-O-Sitam,(1998),130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

## ตรวจสอบ + จัดการค่าว่าง

In [ ]:
India_data.isnull().any()

Name        False
Year         True
Duration     True
Genre        True
Rating       True
Votes        True
Director     True
Actor 1      True
Actor 2      True
Actor 3      True
dtype: bool

In [ ]:
India_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

### ชื่อ

In [ ]:
print(len(India_data[India_data['Name'].isnull()]))
India_data[India_data['Name'].isnull()]

0

Empty DataFrame
Columns: [Name, Year, Duration, Genre, Rating, Votes, Director, Actor 1, Actor 2, Actor 3]
Index: []

In [ ]:
India_data.loc[0,'Name']= '"space"'  #loc ชี้ไปที่ตารางด้วยแถวและคอลัมน์ทีาเราสนใจ จะเปลี่ยนชื่อ

In [ ]:
India_data['Name'].unique()

array(['"space"', '#Gadhvi (He thought he was Gandhi)', '#Homecoming',
       ..., 'Zulmi Raj', 'Zulmi Shikari', 'Zulm-O-Sitam'], dtype=object)

### ปี

In [ ]:
print(len(India_data[India_data['Year'].isnull()]))
India_data[India_data['Year'].isnull()]

528

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,"""space""",NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
16,108 Limited,NaN,NaN,NaN,NaN,NaN,Anand Anddy,Vijay Raaz,Sanjay Mishra,Brahmanandam
23,12 Years,NaN,NaN,Biography,NaN,NaN,Sohail Tatari,NaN,NaN,NaN
37,1911,NaN,NaN,"Drama, History, Sport",NaN,NaN,Nikkhil Advani,John Abraham,NaN,NaN
48,2 GB Ki Life,NaN,NaN,Drama,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
15177,Yakshya,NaN,NaN,Horror,NaN,NaN,Linkan Mahapatra,NaN,NaN,NaN
15315,Yubi Lakpi,NaN,NaN,Biography,NaN,NaN,NaN,NaN,NaN,NaN
15316,Yubi Lukpi,NaN,NaN,Drama,NaN,NaN,Omung Kumar,NaN,NaN,NaN
15337,Zahoor,NaN,NaN,Action,NaN,NaN,Pankaj Batra,Parineeti Chopra,Parmish Verma,Rahul Sharma
15477,Zindagi on the Rocks,NaN,NaN,Drama,NaN,NaN,Ravindra Suryavanshi,Bala Hijam,Pushtii Shakti,Bajrangbali Singh

In [ ]:
India_data['Year'] = India_data['Year'] = India_data['Year'].str.replace('(', '').str.replace(')', '').astype(float)

ผู้กำกับคนเดียวกันน่าจะผลิตหนังในปีใกล้ๆ เคียงกัน

In [ ]:
India_data['Year'].fillna(India_data.groupby('Director')['Year'].transform('mean'))

0        2017.0
1        2019.0
2        2021.0
3        2019.0
4        2010.0
          ...
15504    1988.0
15505    1999.0
15506    2005.0
15507    1988.0
15508    1998.0
Name: Year, Length: 15509, dtype: float64

Director เพราะน่าจะผลิตหนังในช่วงเดียวๆ กัน

In [ ]:
India_data['Year'] = India_data['Year'].fillna(India_data.groupby('Director')['Year'].transform('mean'))

In [ ]:
print(len(India_data[India_data['Year'].isnull()]))
India_data[India_data['Year'].isnull()].head(5)

324

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
16,108 Limited,NaN,NaN,NaN,NaN,NaN,Anand Anddy,Vijay Raaz,Sanjay Mishra,Brahmanandam
48,2 GB Ki Life,NaN,NaN,Drama,NaN,NaN,NaN,NaN,NaN,NaN
93,4 Sum,NaN,96 min,"Crime, Drama, Thriller",NaN,NaN,Neeraj Gwal,Pranav Chandrakar,Yashwant Anand Gupta,Neeraj Uke
112,69 Reality in Us,NaN,NaN,"Drama, Romance, Thriller",NaN,NaN,Samir Khan,NaN,NaN,NaN
122,777 Charlie,NaN,136 min,"Adventure, Comedy, Drama",NaN,NaN,Kiranraj K,Rakshit Shetty,Charlie,Sangeetha Sringeri

### ประเภทหนัง

In [ ]:
print(len(India_data[India_data['Genre'].isnull()]))
India_data[India_data['Genre'].isnull()]

1877

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
16,108 Limited,NaN,NaN,NaN,NaN,NaN,Anand Anddy,Vijay Raaz,Sanjay Mishra,Brahmanandam
19,11 O'Clock,1948.0,NaN,NaN,NaN,NaN,Homi Wadia,Aftab,Sayani Atish,Austin Ki Bachchi
31,150 Seconds Ago,2002.0,112 min,NaN,NaN,NaN,Batul Mukhtiar,NaN,NaN,NaN
65,25th July,1951.0,NaN,NaN,7.6,5,Chitra Mitra,NaN,NaN,NaN
66,26 January,1956.0,NaN,NaN,6.6,7,Ramesh Saigal,Ajit,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
15473,Zindagi Ke Mele,1956.0,NaN,NaN,NaN,NaN,K.B. Lall,Chandrashekhar,Chitra,Dulari
15480,Zindagi Unlimited,2021.0,105 min,NaN,NaN,NaN,Vipin Agnihotri,Amit Pandey,Kanchi Rohela,Kritika Sanghavi
15485,Zingaro,1963.0,NaN,NaN,NaN,NaN,Chandrakant,Bela Bose,Laxmi Chhaya,Aruna Irani
15486,Zingaro,1935.0,NaN,NaN,NaN,NaN,S.N. Bhende,Pushpa,NaN,NaN
15495,Zulf Ke Saye Saye,1983.0,NaN,NaN,NaN,NaN,Anand Sagar,Roohi Berde,Rakesh Pandey,NaN

In [ ]:
India_data_Genre_Na =  India_data[India_data['Genre'].isnull()]
India_data_Genre_Na

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
16,108 Limited,NaN,NaN,NaN,NaN,NaN,Anand Anddy,Vijay Raaz,Sanjay Mishra,Brahmanandam
19,11 O'Clock,1948.0,NaN,NaN,NaN,NaN,Homi Wadia,Aftab,Sayani Atish,Austin Ki Bachchi
31,150 Seconds Ago,2002.0,112 min,NaN,NaN,NaN,Batul Mukhtiar,NaN,NaN,NaN
65,25th July,1951.0,NaN,NaN,7.6,5,Chitra Mitra,NaN,NaN,NaN
66,26 January,1956.0,NaN,NaN,6.6,7,Ramesh Saigal,Ajit,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
15473,Zindagi Ke Mele,1956.0,NaN,NaN,NaN,NaN,K.B. Lall,Chandrashekhar,Chitra,Dulari
15480,Zindagi Unlimited,2021.0,105 min,NaN,NaN,NaN,Vipin Agnihotri,Amit Pandey,Kanchi Rohela,Kritika Sanghavi
15485,Zingaro,1963.0,NaN,NaN,NaN,NaN,Chandrakant,Bela Bose,Laxmi Chhaya,Aruna Irani
15486,Zingaro,1935.0,NaN,NaN,NaN,NaN,S.N. Bhende,Pushpa,NaN,NaN
15495,Zulf Ke Saye Saye,1983.0,NaN,NaN,NaN,NaN,Anand Sagar,Roohi Berde,Rakesh Pandey,NaN

In [ ]:
India_data_Name_dup = India_data[India_data['Name'].duplicated()] #ดูชื่อหนังที่ซ้ำกัน
India_data_Name_dup

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
22,12 O'Clock,2021.0,105 min,"Horror, Thriller",4.4,63,Ram Gopal Varma,Mithun Chakraborty,Makrand Deshpande,Dalip Tahil
101,5 Rifles,2001.0,NaN,Action,NaN,NaN,Hemant Birje,Anu Kashyap,Raza Murad,Paintal
136,A Ballad of Maladies,2016.0,86 min,"Documentary, History, Music",NaN,NaN,Sarvnik Kaur,Tushar Madhav,NaN,NaN
180,Aa Gale Lag Jaa,1994.0,158 min,"Mystery, Romance",4.4,115,Hamid Ali Khan,Jugal Hansraj,Urmila Matondkar,Paresh Rawal
186,Aabroo,1968.0,170 min,"Comedy, Crime, Drama",5.5,21,C.L. Rawal,Ashok Kumar,Vimi,Rehman
...,...,...,...,...,...,...,...,...,...,...
15459,Zindagi,1956.0,NaN,NaN,NaN,NaN,C.L. Dheer,Geeta Bali,NaN,NaN
15460,Zindagi,2000.0,118 min,Romance,2.8,8,Suraj Prakash,Vicky Bhalla,Gayatri,Deepak Jethi
15461,Zindagi,1942.0,NaN,Drama,NaN,NaN,Amiya Chakrabarty,Master Bhagwan,Nalini Jaywant,Ashok Kumar
15467,Zindagi Aur Maut,2002.0,119 min,Action,NaN,NaN,Ramesh U. Lakhiani,Arun Mathur,Anil Nagrath,Amit Pachori
15486,Zingaro,1935.0,NaN,NaN,NaN,NaN,S.N. Bhende,Pushpa,NaN,NaN

In [ ]:
name_genre = {} # สร้าง dict เก็บชื่อหนัง+ประเภท
for i in range(len(India_data)):
    if pd.notna(India_data.loc[i, 'Genre']):  # ใช้ pd.notna เพื่อตรวจสอบว่าไม่เป็นค่าว่าง
        name_genre[India_data.loc[i, 'Name']] = India_data.loc[i, 'Genre']

for i in range(len(India_data)): # เติมประเภทหนัง จากชื่อที่เหมือนกัน ด้วยประเภทที่เจอล่าสุด กรณีซ้ำ
    if pd.isnull(India_data.loc[i, 'Genre']):  # ใช้ pd.isnull เพื่อตรวจสอบค่าว่าง
        if India_data.loc[i, 'Name'] in name_genre:
            India_data.loc[i, 'Genre'] = name_genre[India_data.loc[i, 'Name']]

In [ ]:
print(len(India_data[India_data['Genre'].isnull()]))
India_data[India_data['Genre'].isnull()].head(5)

1393

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
16,108 Limited,NaN,NaN,NaN,NaN,NaN,Anand Anddy,Vijay Raaz,Sanjay Mishra,Brahmanandam
19,11 O'Clock,1948.0,NaN,NaN,NaN,NaN,Homi Wadia,Aftab,Sayani Atish,Austin Ki Bachchi
31,150 Seconds Ago,2002.0,112 min,NaN,NaN,NaN,Batul Mukhtiar,NaN,NaN,NaN
65,25th July,1951.0,NaN,NaN,7.6,5,Chitra Mitra,NaN,NaN,NaN
66,26 January,1956.0,NaN,NaN,6.6,7,Ramesh Saigal,Ajit,NaN,NaN

### Rating

In [ ]:
print(len(India_data[India_data['Rating'].isnull()]))
India_data[India_data['Rating'].isnull()].head(5)

7590

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,"""space""",2017.0,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
2,#Homecoming,2021.0,90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
4,...And Once Again,2010.0,105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
7,.in for Motion,2008.0,59 min,Documentary,NaN,NaN,Anirban Datta,NaN,NaN,NaN
14,101 Ratein,1990.0,NaN,Thriller,NaN,NaN,Harish,Saraswati,Disco Shanti,NaN

IMDb Rating: ใช้ระบบ 10 จุด โดยผู้ชมทั่วไปจะให้คะแนนภาพยนตร์หรือรายการโดยหลังจากได้ชม คะแนนเหล่านี้จะถูกรวมและคำนวณเป็นค่าเฉลี่ยเพื่อสะท้อนถึงคุณภาพหรือความนิยมโดยรวมของผลงานนั้นๆ

In [ ]:
India_data.groupby('Genre')['Rating'].mean().round(1)

Genre
Action                          5.1
Action, Adventure               5.6
Action, Adventure, Biography    7.8
Action, Adventure, Comedy       5.6
Action, Adventure, Crime        5.6
                               ...
Thriller, Action                4.3
Thriller, Musical, Mystery      7.1
Thriller, Mystery               6.5
Thriller, Mystery, Family       6.1
War                             4.3
Name: Rating, Length: 485, dtype: float64

ใช้ .transform('mean') เพื่อสร้าง Series ที่มีขนาดเท่าเดิมกับข้อมูลต้นทาง เพื่อเติมค่าเฉลี่ยเข้าไปที่ตำแหน่งที่มีค่าว่างโดยตรง

In [ ]:
India_data['Rating'] = India_data['Rating'].fillna(India_data.groupby('Genre')['Rating'].transform('mean')).round(1)

In [ ]:
print(len(India_data[India_data['Rating'].isnull()]))
India_data[India_data['Rating'].isnull()].head(5)

1386

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
16,108 Limited,NaN,NaN,NaN,NaN,NaN,Anand Anddy,Vijay Raaz,Sanjay Mishra,Brahmanandam
19,11 O'Clock,1948.0,NaN,NaN,NaN,NaN,Homi Wadia,Aftab,Sayani Atish,Austin Ki Bachchi
31,150 Seconds Ago,2002.0,112 min,NaN,NaN,NaN,Batul Mukhtiar,NaN,NaN,NaN
102,5 Rupees,2018.0,NaN,NaN,NaN,NaN,Piyush Panjuani,Shabana Azmi,Yohaan Panjuani,NaN
136,A Ballad of Maladies,2016.0,86 min,"Documentary, History, Music",NaN,NaN,Sarvnik Kaur,Tushar Madhav,NaN,NaN

### เติมค่าว่างที่เหลือ

In [ ]:
missing_data = India_data.isnull().sum() / len(India_data) * 100
missing_data

Name         0.000000
Year         2.089110
Duration    53.317429
Genre        8.981881
Rating       8.936746
Votes       48.932878
Director     3.385131
Actor 1     10.426204
Actor 2     15.371720
Actor 3     20.272100
dtype: float64

In [ ]:
India_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      15185 non-null  float64
 2   Duration  7240 non-null   object
 3   Genre     14116 non-null  object
 4   Rating    14123 non-null  float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(2), object(8)
memory usage: 1.2+ MB

In [ ]:
India_data['Duration'] = pd.to_numeric(India_data['Duration'].str.replace(' min', '', regex=False), errors='coerce')
India_data['Votes'] = pd.to_numeric(India_data['Votes'].str.replace(',', '', regex=False), errors='coerce')

India_data.fillna({'Year':India_data['Year'].mean(), 'Duration':India_data['Duration'].mean(), 'Votes':0 ,'Rating':India_data['Rating'].mean()}, inplace=True)

In [ ]:
India_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      15509 non-null  float64
 2   Duration  15509 non-null  float64
 3   Genre     14116 non-null  object
 4   Rating    15509 non-null  float64
 5   Votes     15509 non-null  float64
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(4), object(6)
memory usage: 1.2+ MB

In [ ]:
# ลบแถวที่มีค่าว่างในคอลัมน์ที่เลือก
India_data_cleaned = India_data.dropna(subset=['Genre', 'Director', 'Actor 1', 'Actor 2', 'Actor 3'])

In [ ]:
India_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11646 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      11646 non-null  object
 1   Year      11646 non-null  float64
 2   Duration  11646 non-null  float64
 3   Genre     11646 non-null  object
 4   Rating    11646 non-null  float64
 5   Votes     11646 non-null  float64
 6   Director  11646 non-null  object
 7   Actor 1   11646 non-null  object
 8   Actor 2   11646 non-null  object
 9   Actor 3   11646 non-null  object
dtypes: float64(4), object(6)
memory usage: 1000.8+ KB

In [ ]:
missing_data = India_data_cleaned.isnull().sum() / len(India_data_cleaned) * 100
missing_data

Name        0.0
Year        0.0
Duration    0.0
Genre       0.0
Rating      0.0
Votes       0.0
Director    0.0
Actor 1     0.0
Actor 2     0.0
Actor 3     0.0
dtype: float64

# นักแสดงคนไหนที่มักจะพบว่าเล่นหนังด้วยกัน

In [ ]:
df = India_data_cleaned

จัดกลุ่ม Rating ออกเป็น4กลุ่ม โดยอิงจากการกระจายของข้อมูลตามควอไทล์ เพื่อวิเคราะห์ระดับคุณภาพของข้อมูล

In [ ]:
df['Rating_Quantiles'] = pd.qcut(
    df['Rating'],
    q=4,
    labels=['Poor', 'Average', 'Good', 'Excellent']
)

/tmp/ipython-input-2200216844.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating_Quantiles'] = pd.qcut(

แปลงคอลัมน์นักแสดงให้แยกจากกัน

In [ ]:
actors = pd.get_dummies(
    df[['Actor 1','Actor 2','Actor 3']].stack(),
    prefix='Actor'
).groupby(level=0).max()

In [ ]:
rating_dummies = pd.get_dummies(
    df['Rating_Quantiles'],
    prefix='Rating_Quantiles'
)

In [ ]:
data_apri = pd.concat([actors, rating_dummies], axis=1)
data_apri.head()

,Actor_A. Muthu,Actor_A. Nairang,Actor_A. Shah Shikarpuri,Actor_A.H. Shore,Actor_A.K. Agnihotri,Actor_A.K. Hangal,Actor_A.K. Misra,Actor_A.S. Gyani,Actor_A.S. Ravindra Babu,Actor_A.V.M. Rajan,...,Actor_Zoya Hussain,Actor_Zubeida,Actor_Zuber K. Khan,Actor_Zuber Kamal Khan,Actor_Zulfi Sayed,Actor_Zunaid Memon,Rating_Quantiles_Poor,Rating_Quantiles_Average,Rating_Quantiles_Good,Rating_Quantiles_Excellent
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

เลือกเมื่อปรากฏในภาพยนตร์อย่างน้อย 0.1% ของจำนวนภาพยนตร์ทั้งหมด

In [ ]:
from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets = apriori(
    data_apri,
    min_support=0.001,
    use_colnames=True
)

In [ ]:
rules1 = association_rules(
    frequent_itemsets,
    metric="lift",
    min_threshold=1
)

rules1.sort_values('lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
218,(Actor_John Cawas),(Actor_Fearless Nadia),0.001460,0.001631,0.001116,0.764706,468.724458,1.0,0.001114,4.243066,0.999325,0.565217,0.764321,0.724458
219,(Actor_Fearless Nadia),(Actor_John Cawas),0.001631,0.001460,0.001116,0.684211,468.724458,1.0,0.001114,3.162044,0.999497,0.565217,0.683749,0.724458
792,"(Actor_Amit Pachori, Rating_Quantiles_Poor)",(Actor_Sapna Sappu),0.002233,0.003864,0.001030,0.461538,119.446154,1.0,0.001022,1.849967,0.993847,0.203390,0.459450,0.364103
793,(Actor_Sapna Sappu),"(Actor_Amit Pachori, Rating_Quantiles_Poor)",0.003864,0.002233,0.001030,0.266667,119.446154,1.0,0.001022,1.360592,0.995475,0.203390,0.265026,0.364103
47,(Actor_Amit Pachori),(Actor_Sapna Sappu),0.004293,0.003864,0.001975,0.460000,119.048000,1.0,0.001958,1.844696,0.995876,0.319444,0.457905,0.485556
46,(Actor_Sapna Sappu),(Actor_Amit Pachori),0.003864,0.004293,0.001975,0.511111,119.048000,1.0,0.001958,2.036673,0.995446,0.319444,0.509003,0.485556
791,"(Actor_Sapna Sappu, Rating_Quantiles_Poor)",(Actor_Amit Pachori),0.002061,0.004293,0.001030,0.500000,116.460000,1.0,0.001022,1.991413,0.993461,0.193548,0.497844,0.370000
794,(Actor_Amit Pachori),"(Actor_Sapna Sappu, Rating_Quantiles_Poor)",0.004293,0.002061,0.001030,0.240000,116.460000,1.0,0.001022,1.313078,0.995688,0.193548,0.238431,0.370000
45,(Actor_Anil Nagrath),(Actor_Amit Pachori),0.003606,0.004293,0.001460,0.404762,94.277143,1.0,0.001444,1.672787,0.992974,0.226667,0.402195,0.372381
44,(Actor_Amit Pachori),(Actor_Anil Nagrath),0.004293,0.003606,0.001460,0.340000,94.277143,1.0,0.001444,1.509687,0.993659,0.226667,0.337611,0.372381

In [ ]:
rules1.shape

(808, 14)

# นักแสดงคนไหนเล่นหนังประเภทไหน ได้rating Good/Excellent

ตรวจสอบว่านักแสดงคนไหนเล่นไหนประเภทไหน ได้เรตติ้งเท่าไหร่

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

df2 = India_data_cleaned[
    ['Actor 1', 'Actor 2', 'Actor 3', 'Genre', 'Rating_Quantiles']
].copy()

actors_long = df2.melt(
    id_vars=['Genre', 'Rating_Quantiles'],
    value_vars=['Actor 1', 'Actor 2', 'Actor 3'],
    value_name='Actor'
)

actors_long = actors_long.dropna(subset=['Actor'])

actors_long['Genre'] = actors_long['Genre'].str.split(',')

actor_genre_long = actors_long.explode('Genre')
actor_genre_long['Genre'] = actor_genre_long['Genre'].str.strip()

basket = actor_genre_long[['Actor', 'Genre', 'Rating_Quantiles']].copy()

basket['Actor'] = 'Actor_' + basket['Actor'].astype(str)
basket['Genre'] = 'Genre_' + basket['Genre'].astype(str)
basket['Rating_Quantiles'] = 'Rating_' + basket['Rating_Quantiles'].astype(str)

transactions = basket.apply(list, axis=1)

te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

df_te = pd.DataFrame(te_array, columns=te.columns_)

In [ ]:
frequent_itemsets = apriori(
    df_te,
    min_support=0.00065,
    use_colnames=True,
    max_len=3   # Actor + Genre + Rating
)

In [ ]:
rules = association_rules(
    frequent_itemsets,
    metric='confidence',
    min_threshold=0.3
)

In [ ]:
actor_genre_rating_rules = rules[
    rules['antecedents'].apply(
        lambda x: any(i.startswith('Actor_') for i in x)
        and any(i.startswith('Genre_') for i in x)
    ) &
    rules['consequents'].apply(
        lambda x: any(i.startswith('Rating_') for i in x)
    )
].sort_values(['lift', 'confidence'], ascending=False)

In [ ]:
actor_genre_rating_rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
210,"(Actor_Dev Anand, Genre_Drama)",(Rating_Excellent),0.001132,0.281376,0.000877,0.774648,2.753075,1.0,0.000558,3.188896,0.637491,0.003114,0.686412,0.388882
215,"(Actor_Govinda, Genre_Drama)",(Rating_Poor),0.001180,0.271379,0.000749,0.635135,2.340396,1.0,0.000429,1.996960,0.573398,0.002757,0.499239,0.318948
230,"(Genre_Action, Actor_Sanjay Dutt)",(Rating_Poor),0.001562,0.271379,0.000909,0.581633,2.143246,1.0,0.000485,1.741581,0.534253,0.003341,0.425809,0.292491
227,"(Actor_Naseeruddin Shah, Genre_Drama)",(Rating_Excellent),0.001228,0.281376,0.000717,0.584416,2.076995,1.0,0.000372,1.729190,0.519173,0.002545,0.421695,0.293483
235,"(Actor_Shabana Azmi, Genre_Drama)",(Rating_Excellent),0.001451,0.281376,0.000829,0.571429,2.030839,1.0,0.000421,1.676790,0.508330,0.002940,0.403623,0.287187
216,"(Genre_Action, Actor_Jeetendra)",(Rating_Poor),0.001355,0.271379,0.000733,0.541176,1.994169,1.0,0.000366,1.588019,0.499215,0.002696,0.370285,0.271939
223,"(Genre_Action, Actor_Mithun Chakraborty)",(Rating_Poor),0.002535,0.271379,0.001355,0.534591,1.969904,1.0,0.000667,1.565550,0.493612,0.004972,0.361247,0.269792
229,"(Actor_Rajesh Khanna, Genre_Drama)",(Rating_Excellent),0.001483,0.281376,0.000813,0.548387,1.948951,1.0,0.000396,1.591240,0.487626,0.002883,0.371559,0.275638
237,"(Actor_Shashi Kapoor, Genre_Drama)",(Rating_Excellent),0.001531,0.281376,0.000829,0.541667,1.925067,1.0,0.000398,1.567908,0.481274,0.002939,0.362207,0.272307
205,"(Actor_Amitabh Bachchan, Genre_Drama)",(Rating_Excellent),0.002168,0.281376,0.001068,0.492647,1.750852,1.0,0.000458,1.416419,0.429781,0.003781,0.293994,0.248222

In [ ]:
actor_genre_rating_rules.shape

(17, 14)

ดูเฉพาะ Rating Good/Excellent

In [ ]:
good_ratings = ['Rating_Good', 'Rating_Excellent']

actor_genre_good_rules = rules[
    rules['antecedents'].apply(
        lambda x: any(i.startswith('Actor_') for i in x)
        and any(i.startswith('Genre_') for i in x)
    ) &
    rules['consequents'].apply(
        lambda x: any(i in good_ratings for i in x)
    )
].sort_values(['lift', 'confidence'], ascending=False)

In [ ]:
actor_genre_good_rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
210,"(Actor_Dev Anand, Genre_Drama)",(Rating_Excellent),0.001132,0.281376,0.000877,0.774648,2.753075,1.0,0.000558,3.188896,0.637491,0.003114,0.686412,0.388882
227,"(Actor_Naseeruddin Shah, Genre_Drama)",(Rating_Excellent),0.001228,0.281376,0.000717,0.584416,2.076995,1.0,0.000372,1.729190,0.519173,0.002545,0.421695,0.293483
235,"(Actor_Shabana Azmi, Genre_Drama)",(Rating_Excellent),0.001451,0.281376,0.000829,0.571429,2.030839,1.0,0.000421,1.676790,0.508330,0.002940,0.403623,0.287187
229,"(Actor_Rajesh Khanna, Genre_Drama)",(Rating_Excellent),0.001483,0.281376,0.000813,0.548387,1.948951,1.0,0.000396,1.591240,0.487626,0.002883,0.371559,0.275638
237,"(Actor_Shashi Kapoor, Genre_Drama)",(Rating_Excellent),0.001531,0.281376,0.000829,0.541667,1.925067,1.0,0.000398,1.567908,0.481274,0.002939,0.362207,0.272307
205,"(Actor_Amitabh Bachchan, Genre_Drama)",(Rating_Excellent),0.002168,0.281376,0.001068,0.492647,1.750852,1.0,0.000458,1.416419,0.429781,0.003781,0.293994,0.248222
207,"(Actor_Ashok Kumar, Genre_Drama)",(Rating_Excellent),0.002567,0.281376,0.001228,0.478261,1.699724,1.0,0.000505,1.377364,0.412729,0.004342,0.273975,0.241312
233,"(Actor_Sanjeev Kumar, Genre_Drama)",(Rating_Excellent),0.001403,0.281376,0.000670,0.477273,1.696213,1.0,0.000275,1.374760,0.411028,0.002374,0.272600,0.239826
214,"(Actor_Dharmendra, Genre_Drama)",(Rating_Excellent),0.002089,0.281376,0.000829,0.396947,1.410736,1.0,0.000241,1.191643,0.291759,0.002933,0.160823,0.199946

In [ ]:
actor_genre_good_rules.shape

(9, 14)

Slied : https://www.canva.com/design/DAHAIu-27wA/JNl3RrqI0YX9M_q8EChv6A/edit