<a href="https://colab.research.google.com/github/bamSirikorn/BSC_DPDM2025/blob/main/Midterm_663020299_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data

In [293]:
import pandas as pd
import numpy as np

##ข้อ1

In [294]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [295]:
Dailyrain = pd.read_csv('/content/drive/MyDrive/midtermbsc_2025/Daily rain - (Statistics 2012-2024)/hii_daily_rain.csv')
stations = pd.read_csv('/content/drive/MyDrive/midtermbsc_2025/Input - (Operation Daily rain from API_ 2025)/Stations in the model_HII.csv')
output = pd.read_csv('/content/drive/MyDrive/midtermbsc_2025/Output - (Clean monthly rain - 2025)/Y_monthly_rain_HII_operation.csv')

In [296]:
Dailyrain

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3768458,YOM016,2024-11-25 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768459,YOM016,2024-11-26 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768460,YOM016,2024-11-27 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768461,YOM016,2024-11-28 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768462,YOM016,2024-11-29 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily

In [297]:
Dailyrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3768463 entries, 0 to 3768462
Data columns (total 13 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  object
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
dtypes: float64(3), object(10)
memory usage: 373.8+ MB

In [298]:
stations.rename(columns={'Node': 'station_code'}, inplace=True)

In [299]:
stations

    station_code        Lat        Long
0           ACRU  15.788054  104.642235
1           BBHN   9.536913   98.579490
2           BBUA  17.372976  103.984436
3           BCNG  17.386840  103.290870
4           BDAR  14.587073  102.495190
..           ...        ...         ...
380       YOM003  18.265924  100.177060
381       YOM008  16.708166  100.171780
382       YOM009  16.310750  100.271750
383       YOM010  18.133717  100.124596
384       YOM012  17.021260   99.819710

[385 rows x 3 columns]

In [300]:
output

      Node   rain  month  year
0     ACRU   83.0      7  2025
1     ACRU  164.8      8  2025
2     ACRU  248.6      9  2025
3     ACRU   48.4     10  2025
4     ACRU   52.2     11  2025
5     ACRU    0.2     12  2025
6     BBHN  391.6      7  2025
7     BBHN  641.2      8  2025
8     BBHN  517.6      9  2025
9     BBHN  198.8     10  2025
10    BBHN  224.0     11  2025
11    BBHN    5.8     12  2025
12    BBUA  135.6      7  2025
13    BBUA   58.0      8  2025
14    BBUA   14.8      9  2025
15    BBUA   71.8     10  2025
16  YOM012  100.6     11  2025
17  YOM012    8.0     12  2025

In [301]:
import os
import pandas as pd
#การสร้าง ตัวแปร เพื่อเก็บ "ที่อยู่ (Path)" ของโฟลเดอร์ใน Google Drive  (เดือน 7 ถึง 12 ปี 2025)
folder_path = '/content/drive/MyDrive/midtermbsc_2025/Input - (Operation Daily rain from API_ 2025)/2025-07/'
folder_path2 = '/content/drive/MyDrive/midtermbsc_2025/Input - (Operation Daily rain from API_ 2025)/2025-08/'
folder_path3 = '/content/drive/MyDrive/midtermbsc_2025/Input - (Operation Daily rain from API_ 2025)/2025-09/'
folder_path4 = '/content/drive/MyDrive/midtermbsc_2025/Input - (Operation Daily rain from API_ 2025)/2025-10/'
folder_path5 = '/content/drive/MyDrive/midtermbsc_2025/Input - (Operation Daily rain from API_ 2025)/2025-11/'
folder_path6 = '/content/drive/MyDrive/midtermbsc_2025/Input - (Operation Daily rain from API_ 2025)/2025-12/'

#นำตัวแปรที่เก็บ Path ทั้งหมดมารวมกันไว้ใน List เพื่อให้ง่ายต่อการสั่งให้โปรแกรมทำงานวนซ้ำ (Loop) ทีเดียวทุกโฟลเดอร์
all_folder_paths = [
    folder_path,
    folder_path2,
    folder_path3,
    folder_path4,
    folder_path5,
    folder_path6
]
#สร้างลิสต์ว่างๆ ไว้รอเก็บ "แผ่นข้อมูล (DataFrame)" ที่อ่านได้จากแต่ละไฟล์
df_list = []
#สร้างตัวนับจำนวนไฟล์ เริ่มต้นที่ 0 เพื่อเอาไว้สรุปตอนท้ายว่าอ่านไปได้กี่ไฟล์แล้ว
file_count = 0
#การใช้ Loop เพื่ออ่านไฟล์ CSV ทุกไฟล์
#เริ่มเข้าไปดูในแต่ละโฟลเดอร์ตามลิสต์ที่เราทำไว้
#สั่งให้โปรแกรมดูว่าในโฟลเดอร์นั้นมีไฟล์อะไรบ้าง
#เลือกเฉพาะไฟล์ที่นามสกุลลงท้ายด้วย .csv เท่านั้น
for path in all_folder_paths:
    csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]
    for csv_file in csv_files:
        file_path = os.path.join(path, csv_file)
        df = pd.read_csv(file_path)
        df_list.append(df)
        file_count += 1

combined_input_df = pd.concat(df_list, ignore_index=True)

print(f"Successfully combined {file_count} CSV files from all specified folders into one DataFrame.")
display(combined_input_df.tail())

Successfully combined 187 CSV files from all specified folders into one DataFrame.

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,station_code,value
180695,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,254.0,BJAN,2025-12-13,NaN,NaN
180696,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,308.0,WEI012,2025-12-13,NaN,NaN
180697,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,770.0,GLF003,2025-12-13,NaN,NaN
180698,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,1109588.0,ONE099,2025-12-13,NaN,NaN
180699,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,286.0,TSUD,2025-12-13,NaN,NaN

##ข้อ2

In [302]:
# Drop the 'station_code' and 'value' columns from combined_input_df
combined_input_df = combined_input_df.drop(columns=['station_code', 'value'])

print("combined_input_df after dropping 'station_code' and 'value' columns:")
combined_input_df.info()

combined_input_df after dropping 'station_code' and 'value' columns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180700 entries, 0 to 180699
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       176886 non-null  object
 1   rainfall_datetime_calc  176886 non-null  object
 2   rainfall_value          176882 non-null  float64
 3   tele_station_id         173072 non-null  float64
 4   tele_station_oldcode    168021 non-null  object
 5   measure_datetime        180700 non-null  object
dtypes: float64(2), object(4)
memory usage: 8.3+ MB

In [303]:
combined_input_df.rename(
    columns={'tele_station_oldcode': 'station_code'},
    inplace=True
)

In [304]:
combined_input_df

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,station_code,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09
3,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,277.0,BNAK,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09
...,...,...,...,...,...,...
180695,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,254.0,BJAN,2025-12-13
180696,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,308.0,WEI012,2025-12-13
180697,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,770.0,GLF003,2025-12-13
180698,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,1109588.0,ONE099,2025-12-13
180699,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,286.0,TSUD,2025-12-13

In [305]:
combined_input_df.isnull().sum()

rainfall_datetime          3814
rainfall_datetime_calc     3814
rainfall_value             3818
tele_station_id            7628
station_code              12679
measure_datetime              0
dtype: int64

In [306]:
print("ข้อมูลสถานีหลังกรอง")
display(combined_input_df['station_code'].value_counts())

ข้อมูลสถานีหลังกรอง

station_code
TKRA      184
TBW027    184
TKNT      184
BGBO      184
BNPK      184
         ...
MOU256      1
MOU292      1
MOU098      1
FOP009      1
DMH018      1
Name: count, Length: 1514, dtype: int64

In [307]:
combined_input_df

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,station_code,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09
3,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,277.0,BNAK,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09
...,...,...,...,...,...,...
180695,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,254.0,BJAN,2025-12-13
180696,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,308.0,WEI012,2025-12-13
180697,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,770.0,GLF003,2025-12-13
180698,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,1109588.0,ONE099,2025-12-13
180699,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,286.0,TSUD,2025-12-13

In [308]:
# --- ส่วนที่ 1: ดึงรายชื่อรหัสสถานีที่ถูกต้อง (Master List) ---
# ดึงค่า 'station_code' จากตาราง stations มาเก็บไว้แบบไม่ซ้ำกัน (unique)
valid_station_codes = stations['station_code'].unique()

# --- ส่วนที่ 2: กรองข้อมูลให้เหลือเฉพาะสถานีที่มีตัวตนอยู่จริง ---
# เลือกเฉพาะแถวใน combined_input_df ที่ค่า 'station_code' ปรากฏอยู่ในลิสต์ valid_station_codes เท่านั้น
filtered_combined_df = combined_input_df[combined_input_df['station_code'].isin(valid_station_codes)]

# --- ส่วนที่ 3: แสดงผลสรุปการกรองข้อมูล ---
# พิมพ์จำนวนแถวก่อนกรอง
print(f"Original combined_input_df rows: {len(combined_input_df)}")

# พิมพ์จำนวนแถวหลังกรอง (ถ้าลดลง แสดงว่ามีรหัสสถานีในไฟล์ CSV ที่ไม่มีอยู่ในฐานข้อมูลหลัก)
print(f"Filtered combined_df rows: {len(filtered_combined_df)}")

# แสดงตัวอย่างข้อมูล 5 แถวแรกที่ผ่านการกรองแล้ว
print("Head of the filtered combined_input_df:")
display(filtered_combined_df.head())

Original combined_input_df rows: 180700
Filtered combined_df rows: 66275
Head of the filtered combined_input_df:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,station_code,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09
5,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.6,294.0,BNMK,2025-07-09

##ข้อ3

In [309]:
df = filtered_combined_df.copy() # Corrected variable name
df['measure_datetime'] = pd.to_datetime(df['measure_datetime'])

dates = pd.date_range(df['measure_datetime'].min(),
                      df['measure_datetime'].max())

full = pd.MultiIndex.from_product(
    [df['station_code'].unique(), dates], # Use 'station_code' as 'tele_station_oldcode' was renamed
    names=['station_code', 'measure_datetime'] # Use 'station_code'
).to_frame(index=False)

missing = (full.merge(df[['station_code','measure_datetime','rainfall_value']], # Use 'station_code'
                       how='left')
                .assign(missing=lambda x: x['rainfall_value'].isna())
                .groupby('station_code')['missing'] # Use 'station_code'
                .agg(missing_count='sum'))

result = (missing
          .assign(total_expected=len(dates),
                  missing_proportion=lambda x: x['missing_count']/len(dates))
          .sort_values('missing_proportion', ascending=False))

result

              missing_count  total_expected  missing_proportion
station_code
NPI002                  169             184            0.918478
WAN005                  148             184            0.804348
CHI010                  142             184            0.771739
CHNA                    138             184            0.750000
BPTG                    133             184            0.722826
...                     ...             ...                 ...
WTBT                      0             184            0.000000
WTLG                      0             184            0.000000
WTSG                      0             184            0.000000
WWST                      0             184            0.000000
YGHM                      0             184            0.000000

[384 rows x 3 columns]

## ข้อ4 ลบสถานีที่ข้อมูลหายเกิน0.2

In [310]:
# Identify stations to be removed (missing_proportion > 0.2)
removed_stations_df = result[result['missing_proportion'] > 0.2]

# Identify stations to be kept (missing_proportion <= 0.2)
remaining_stations_df = result[result['missing_proportion'] <= 0.2]

print("--- รายชื่อสถานีที่ถูกคัดออก (Missing Proportion > 20%) ---")
display(removed_stations_df)

--- รายชื่อสถานีที่ถูกคัดออก (Missing Proportion > 20%) ---

              missing_count  total_expected  missing_proportion
station_code
NPI002                  169             184            0.918478
WAN005                  148             184            0.804348
CHI010                  142             184            0.771739
CHNA                    138             184            0.750000
BPTG                    133             184            0.722826
BKK017                  131             184            0.711957
PSLT                    130             184            0.706522
YCUM                    128             184            0.695652
PRN001                  128             184            0.695652
PAS008                  127             184            0.690217
TUKW                    123             184            0.668478
BNGR                    121             184            0.657609
NAPK                    115             184            0.625000
BSKJ                    110             184            0.597826
CHI013                  109             184            0.592391
MEWG                    107             184            0.581522
NASW                    107             184            0.581522
NNPT                    103             184            0.559783
CEHM                    100             184            0.543478
DGSL                     97             184            0.527174
BKHN                     90             184            0.489130
YOM001                   85             184            0.461957
DCCT                     82             184            0.445652
BNLG                     74             184            0.402174
MNRM                     67             184            0.364130
PMPN                     66             184            0.358696
BSPN                     65             184            0.353261
CGKM                     65             184            0.353261
SKM004                   62             184            0.336957
NEAK                     57             184            0.309783
CTKN                     55             184            0.298913
NGPI                     54             184            0.293478
SGKW                     48             184            0.260870
SKE001                   47             184            0.255435
TPI007                   46             184            0.250000
VLGE33                   46             184            0.250000
NKSG                     46             184            0.250000
KON005                   45             184            0.244565
CPY010                   42             184            0.228261
BLKO                     41             184            0.222826
NGCG                     40             184            0.217391
LMSK                     39             184            0.211957
MMMO                     38             184            0.206522
KKTO                     38             184            0.206522
SLA002                   37             184            0.201087

In [311]:
print("\n--- รายชื่อสถานีที่เหลืออยู่ (Missing Proportion <= 20%) ---")
display(remaining_stations_df)

--- รายชื่อสถานีที่เหลืออยู่ (Missing Proportion <= 20%) ---

              missing_count  total_expected  missing_proportion
station_code
WNKH                     35             184            0.190217
VLGE31                   35             184            0.190217
LK13                     31             184            0.168478
WBYN                     29             184            0.157609
STH011                   23             184            0.125000
...                     ...             ...                 ...
WTBT                      0             184            0.000000
WTLG                      0             184            0.000000
WTSG                      0             184            0.000000
WWST                      0             184            0.000000
YGHM                      0             184            0.000000

[339 rows x 3 columns]

In [312]:
filtered_combined_df.isnull().sum()

rainfall_datetime            0
rainfall_datetime_calc       0
rainfall_value               1
tele_station_id           1023
station_code                 0
measure_datetime             0
dtype: int64

รวมไฟล์

In [313]:
## รายชื่อ station_code ที่ผ่านเกณฑ์ (missing ≤ 20%)
remaining_station_codes = remaining_stations_df.index

## เลือกข้อมูลเฉพาะสถานีที่ยังเหลือ
filtered_remaining_df = filtered_combined_df[
    filtered_combined_df['station_code'].isin(remaining_station_codes)
].copy()

print(f"Rows after keeping valid stations: {len(filtered_remaining_df)}")
display(filtered_remaining_df.head())

Rows after keeping valid stations: 61835

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,station_code,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09
5,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.6,294.0,BNMK,2025-07-09
9,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,234.0,BDAR,2025-07-09

##ข้อ5

In [319]:
import pandas as pd

## =========================================================
## STEP 1: เตรียมข้อมูลรายวัน
## =========================================================
df = Dailyrain.copy()

df['measure_datetime'] = pd.to_datetime(df['measure_datetime'])

## สร้าง Day of Year (DOY)
df['doy'] = df['measure_datetime'].dt.dayofyear


## =========================================================
## STEP 2: ตรวจชื่อคอลัมน์ฝน
## =========================================================
RAIN_COL = 'data'   # <<<< แก้ตรงนี้ให้ตรงกับ df.columns (เดิมคือ 'rain')


## =========================================================
## STEP 3: คำนวณ Median ฝนย้อนหลัง
## แยกตามสถานี + DOY
## =========================================================
median_doy = (
    df.groupby(['station_code', 'doy'])[RAIN_COL]
      .median()
      .reset_index()
      .rename(columns={RAIN_COL: 'rainfall_median'})
)


## =========================================================
## STEP 4: สร้าง Full Grid
## =========================================================
dates = pd.date_range(
    df['measure_datetime'].min(),
    df['measure_datetime'].max()
)

full_grid = pd.MultiIndex.from_product(
    [df['station_code'].unique(), dates],
    names=['station_code', 'measure_datetime']
).to_frame(index=False)

full_grid['doy'] = full_grid['measure_datetime'].dt.dayofyear


## =========================================================
## STEP 5: merge + เติมค่า median
## =========================================================
df_imputed = (
    full_grid
    .merge(
        df[['station_code', 'measure_datetime', RAIN_COL]],
        how='left'
    )
    .merge(
        median_doy,
        on=['station_code', 'doy'],
        how='left'
    )
)

df_imputed[RAIN_COL] = (
    df_imputed[RAIN_COL]
    .fillna(df_imputed['rainfall_median'])
)

df_imputed = df_imputed.drop(columns='rainfall_median')


## =========================================================
## STEP 6: Output
## =========================================================
daily_rainfall_doy_median_filled = df_imputed

display(daily_rainfall_doy_median_filled.head())

  station_code          measure_datetime  doy  data
0         ABRT 2012-01-01 07:00:00+07:00    1   0.0
1         ABRT 2012-01-02 07:00:00+07:00    2   0.0
2         ABRT 2012-01-03 07:00:00+07:00    3   0.0
3         ABRT 2012-01-04 07:00:00+07:00    4   0.0
4         ABRT 2012-01-05 07:00:00+07:00    5   0.0

##ข้อ 6

เหตุผลทางสถิติในการเลือกใช้ค่ามัธยฐาน (Median) แทนค่าเฉลี่ย (Mean) ในการวิเคราะห์ปริมาณน้ำฝน
ในการวิเคราะห์ข้อมูลทางด้านอุตุนิยมวิทยา โดยเฉพาะปริมาณน้ำฝน (Rainfall Data) การเลือกใช้ ค่ามัธยฐาน (Median) เป็นตัวแทนของข้อมูลมีความเหมาะสมมากกว่าการใช้ค่าเฉลี่ยเลขคณิต (Mean) ด้วยเหตุผลหลักดังนี้:

1. ความทนทานต่อค่าสุดโต่ง (Robustness to Outliers) ข้อมูลปริมาณน้ำฝนมักปรากฏค่าที่สูงผิดปกติ (Extreme Events) เช่น สภาวะฝนตกหนักจากพายุหรือมรสุม ซึ่งค่าเหล่านี้จะมีปริมาณสูงกว่าปกติหลายเท่าตัว หากใช้ค่าเฉลี่ยเลขคณิต ข้อมูลที่สูงผิดปกติเพียงไม่กี่ค่าจะดึงค่าเฉลี่ยให้สูงขึ้นเกินความเป็นจริง ส่งผลให้การพยากรณ์หรือการตั้งค่าปกติ (Normal Range) คลาดเคลื่อนได้ ในขณะที่ค่ามัธยฐานจะไม่ได้รับผลกระทบจากค่าสุดโต่งเหล่านี้ ทำให้สะท้อนภาพรวมของเหตุการณ์ที่เกิดขึ้นส่วนใหญ่ได้อย่างแม่นยำกว่า

2. ลักษณะการกระจายตัวของข้อมูลแบบไม่สมมาตร (Non-normal Distribution) โดยธรรมชาติ ข้อมูลปริมาณน้ำฝนจะมีการกระจายตัวแบบเบ้ขวา (Right-skewed Distribution) เนื่องจากมีจำนวนวันที่ฝนไม่ตกหรือตกน้อยเป็นจำนวนมาก และมีเพียงไม่กี่วันที่มีฝนตกหนักมาก ในทางสถิติ เมื่อข้อมูลมีการกระจายตัวไม่เป็นรูปโค้งปกติ (Non-Gaussian distribution) ค่าเฉลี่ยจะถูกดึงไปทางทิศทางของหางข้อมูล (Skew) ทำให้ค่ามัธยฐานซึ่งเป็นค่าที่อยู่ตำแหน่งกึ่งกลางของข้อมูลทั้งหมด เป็นตัวแทนที่มีเสถียรภาพมากกว่าในการระบุ "ค่าปกติ" ของพื้นที่นั้นๆ

3. การสะท้อนความเป็นไปได้จริงในเชิงพื้นที่ (Representativeness) การใช้ค่ามัธยฐานช่วยให้ผู้บริหารจัดการน้ำหรือนักวิเคราะห์มองเห็น "ค่ากลางที่เกิดขึ้นจริง" ของสถานีนั้นๆ ได้ดีกว่าค่าเฉลี่ย ซึ่งมักเป็นค่าทางตัวเลขที่ไม่เคยเกิดขึ้นจริงในสถานการณ์ปกติ การใช้ค่ามัธยฐานจึงช่วยลดความเสี่ยงในการประเมินทรัพยากรน้ำเกินจริง (Overestimation) ส่งผลให้การวางแผนรับมือภัยแล้งหรือการจัดสรรน้ำมีประสิทธิภาพและสอดคล้องกับสภาพข้อเท็จจริงในเชิงพื้นที่มากยิ่งขึ้น

##ข้อ7

In [321]:
import pandas as pd

## =========================================================
## STEP 1: เตรียมข้อมูลฝนย้อนหลัง
## =========================================================
hist = Dailyrain.copy()

hist['measure_datetime'] = pd.to_datetime(hist['measure_datetime'])
# Rename 'data' column to 'rainfall_value' to match expectation
hist.rename(columns={'data': 'rainfall_value'}, inplace=True)

## แยก year / month
hist['year'] = hist['measure_datetime'].dt.year
hist['month'] = hist['measure_datetime'].dt.month


## =========================================================
## STEP 2: ใช้เฉพาะข้อมูลย้อนหลัง (ไม่เอา 2025)
## =========================================================
hist_past = hist[hist['year'] < 2025]


## =========================================================
## STEP 3: กรองเฉพาะสถานีที่เหลืออยู่
## =========================================================
valid_stations = remaining_stations_df.index.tolist()

hist_past_filtered = hist_past[
    hist_past['station_code'].isin(valid_stations)
]


## =========================================================
## STEP 4: กรองเฉพาะเดือน 7–12
## =========================================================
hist_past_filtered = hist_past_filtered[
    hist_past_filtered['month'].between(7, 12)
]


## =========================================================
## STEP 5: คำนวณผลรวมปริมาณน้ำฝนรายเดือน
## =========================================================
monthly_sum = (
    hist_past_filtered
    .groupby(['station_code', 'month'], as_index=False)
    ['rainfall_value']
    .sum()
)


## =========================================================
## STEP 6: ใส่ปี 2025 (label)
## =========================================================
monthly_sum['year'] = 2025


## =========================================================
## STEP 7: จัดรูปแบบ Output
## =========================================================
output_monthly_rainfall = (
    monthly_sum
    .rename(columns={
        'station_code': 'Node',
        'rainfall_value': 'rain'
    })
    [['Node', 'rain', 'month', 'year']]
    .sort_values(['Node', 'month'])
    .reset_index(drop=True)
)


## =========================================================
## STEP 8: ตรวจสอบผลลัพธ์
## =========================================================
print("จำนวนสถานีที่ใช้:", output_monthly_rainfall['Node'].nunique())
print("จำนวนแถวทั้งหมด:", len(output_monthly_rainfall))

output_monthly_rainfall

จำนวนสถานีที่ใช้: 339
จำนวนแถวทั้งหมด: 2034

        Node    rain  month  year
0       ACRU  2949.4      7  2025
1       ACRU  1947.0      8  2025
2       ACRU  2757.0      9  2025
3       ACRU   592.8     10  2025
4       ACRU   274.8     11  2025
...      ...     ...    ...   ...
2029  YOM012  1512.0      8  2025
2030  YOM012  2440.0      9  2025
2031  YOM012  1881.6     10  2025
2032  YOM012   232.2     11  2025
2033  YOM012    81.8     12  2025

[2034 rows x 4 columns]

In [322]:
from google.colab import files

## บันทึกเป็น CSV
file_name = "monthly_rainfall_2025.csv"
output_monthly_rainfall.to_csv(file_name, index=False, encoding='utf-8-sig')

# ## คำสั่งเปิดหน้าต่าง Download
# files.download(file_name)

#Drive 663020299-7

Drive (https://drive.google.com/drive/folders/1ol_BSzEFo2eEWb-HOF50XFZl3SNUq2fH?usp=sharing://)